-- Create the company table with all columns from the CSV
CREATE TABLE public.company (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  company_id INTEGER UNIQUE,
  company_type TEXT,
  name TEXT NOT NULL,
  short_name TEXT,
  logo_url TEXT,
  category TEXT,
  incorporation_year INTEGER,
  overview_text TEXT,
  nature_of_company TEXT,
  headquarters_address TEXT,
  operating_countries TEXT,
  office_count TEXT,
  office_locations TEXT,
  employee_size TEXT,
  vision_statement TEXT,
  mission_statement TEXT,
  core_values TEXT,
  history_timeline TEXT,
  recent_news TEXT,
  website_url TEXT,
  linkedin_url TEXT,
  twitter_handle TEXT,
  facebook_url TEXT,
  instagram_url TEXT,
  primary_contact_email TEXT,
  primary_phone_number TEXT,
  regulatory_status TEXT,
  legal_issues TEXT,
  esg_ratings TEXT,
  supply_chain_dependencies TEXT,
  geopolitical_risks TEXT,
  macro_risks TEXT,
  carbon_footprint TEXT,
  ethical_sourcing TEXT,
  marketing_video_url TEXT,
  customer_testimonials TEXT,
  website_quality TEXT,
  website_rating TEXT,
  website_traffic_rank TEXT,
  social_media_followers TEXT,
  glassdoor_rating TEXT,
  indeed_rating TEXT,
  google_rating TEXT,
  awards_recognitions TEXT,
  brand_sentiment_score TEXT,
  event_participation TEXT,
  pain_points_addressed TEXT,
  focus_sectors TEXT,
  offerings_description TEXT,
  top_customers TEXT,
  core_value_proposition TEXT,
  unique_differentiators TEXT,
  competitive_advantages TEXT,
  weaknesses_gaps TEXT,
  key_challenges_needs TEXT,
  key_competitors TEXT,
  market_share_percentage TEXT,
  sales_motion TEXT,
  customer_concentration_risk TEXT,
  exit_strategy_history TEXT,
  benchmark_vs_peers TEXT,
  future_projections TEXT,
  strategic_priorities TEXT,
  industry_associations TEXT,
  case_studies TEXT,
  go_to_market_strategy TEXT,
  innovation_roadmap TEXT,
  product_pipeline TEXT,
  tam TEXT,
  sam TEXT,
  som TEXT,
  leave_policy TEXT,
  health_support TEXT,
  fixed_vs_variable_pay TEXT,
  bonus_predictability TEXT,
  esops_incentives TEXT,
  family_health_insurance TEXT,
  relocation_support TEXT,
  lifestyle_benefits TEXT,
  hiring_velocity TEXT,
  employee_turnover TEXT,
  avg_retention_tenure TEXT,
  diversity_metrics TEXT,
  work_culture_summary TEXT,
  manager_quality TEXT,
  psychological_safety TEXT,
  feedback_culture TEXT,
  diversity_inclusion_score TEXT,
  ethical_standards TEXT,
  burnout_risk TEXT,
  layoff_history TEXT,
  mission_clarity TEXT,
  sustainability_csr TEXT,
  crisis_behavior TEXT,
  annual_revenue TEXT,
  annual_profit TEXT,
  revenue_mix TEXT,
  valuation TEXT,
  yoy_growth_rate TEXT,
  profitability_status TEXT,
  key_investors TEXT,
  recent_funding_rounds TEXT,
  total_capital_raised TEXT,
  customer_acquisition_cost TEXT,
  customer_lifetime_value TEXT,
  cac_ltv_ratio TEXT,
  churn_rate TEXT,
  net_promoter_score TEXT,
  burn_rate TEXT,
  runway_months TEXT,
  burn_multiplier TEXT,
  remote_policy_details TEXT,
  typical_hours TEXT,
  overtime_expectations TEXT,
  weekend_work TEXT,
  flexibility_level TEXT,
  location_centrality TEXT,
  public_transport_access TEXT,
  cab_policy TEXT,
  airport_commute_time TEXT,
  office_zone_type TEXT,
  area_safety TEXT,
  safety_policies TEXT,
  infrastructure_safety TEXT,
  emergency_preparedness TEXT,
  ceo_name TEXT,
  ceo_linkedin_url TEXT,
  key_leaders TEXT,
  warm_intro_pathways TEXT,
  decision_maker_access TEXT,
  contact_person_name TEXT,
  contact_person_title TEXT,
  contact_person_email TEXT,
  contact_person_phone TEXT,
  board_members TEXT,
  training_spend TEXT,
  onboarding_quality TEXT,
  learning_culture TEXT,
  exposure_quality TEXT,
  mentorship_availability TEXT,
  internal_mobility TEXT,
  promotion_clarity TEXT,
  tools_access TEXT,
  role_clarity TEXT,
  early_ownership TEXT,
  work_impact TEXT,
  execution_thinking_balance TEXT,
  automation_level TEXT,
  cross_functional_exposure TEXT,
  company_maturity TEXT,
  brand_value TEXT,
  client_quality TEXT,
  exit_opportunities TEXT,
  skill_relevance TEXT,
  external_recognition TEXT,
  network_strength TEXT,
  global_exposure TEXT,
  technology_partners TEXT,
  intellectual_property TEXT,
  r_and_d_investment TEXT,
  ai_ml_adoption_level TEXT,
  tech_stack TEXT,
  cybersecurity_posture TEXT,
  partnership_ecosystem TEXT,
  tech_adoption_rating TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.company ENABLE ROW LEVEL SECURITY;

-- Create public read policy for all users (placement intelligence is public data)
CREATE POLICY "Companies are publicly readable" 
ON public.company 
FOR SELECT 
USING (true);

-- Create index for common queries
CREATE INDEX idx_company_category ON public.company(category);
CREATE INDEX idx_company_name ON public.company(name);
CREATE INDEX idx_company_employee_size ON public.company(employee_size);

-- Enable realtime for the company table
ALTER PUBLICATION supabase_realtime ADD TABLE public.company;

-- Create function to update timestamps
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_company_updated_at
BEFORE UPDATE ON public.company
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();